WIP

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -41,73 +41,73 @@ jobs:
         run: echo "version=$(ruby -e 'puts Gem::Specification::load(Dir.glob("*.gemspec").first).version')" >> "$GITHUB_OUTPUT"
 
       # Check if the gem version is already published
-      - name: Verify gem version
-        continue-on-error: ${{ inputs.force }}
-        env:
-          GEM_VERSION: ${{ steps.version.outputs.version }}
-        run: |
-          if gem search datadog --exact --remote --version "$GEM_VERSION" | grep -q "($GEM_VERSION)"; then
-            echo "::error::Version $GEM_VERSION is already published"
-            exit 1
-          else
-            echo "Version $GEM_VERSION is not published yet"
-          fi
+      # - name: Verify gem version
+      #   continue-on-error: ${{ inputs.force }}
+      #   env:
+      #     GEM_VERSION: ${{ steps.version.outputs.version }}
+      #   run: |
+      #     if gem search datadog --exact --remote --version "$GEM_VERSION" | grep -q "($GEM_VERSION)"; then
+      #       echo "::error::Version $GEM_VERSION is already published"
+      #       exit 1
+      #     else
+      #       echo "Version $GEM_VERSION is not published yet"
+      #     fi
 
       # Check if there is a draft release for this version
       # API: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases
-      - name: Verify draft release
-        continue-on-error: ${{ inputs.force }}
-        env:
-          GEM_VERSION: ${{ steps.version.outputs.version }}
-        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
-        with:
-          script: |
-            const { data: releases } = await github.rest.repos.listReleases({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-            });
+      # - name: Verify draft release
+      #   continue-on-error: ${{ inputs.force }}
+      #   env:
+      #     GEM_VERSION: ${{ steps.version.outputs.version }}
+      #   uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+      #   with:
+      #     script: |
+      #       const { data: releases } = await github.rest.repos.listReleases({
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #       });
 
-            console.log(releases);
+      #       console.log(releases);
 
-            const versionTag = `v${process.env.GEM_VERSION}`;
-            const draftRelease = releases.find(
-              release => release.tag_name === versionTag && release.draft === true
-            );
+      #       const versionTag = `v${process.env.GEM_VERSION}`;
+      #       const draftRelease = releases.find(
+      #         release => release.tag_name === versionTag && release.draft === true
+      #       );
 
-            if (!draftRelease) {
-              core.setFailed(`No draft release found with tag ${versionTag}. Please create a draft release first.`);
-              return;
-            }
+      #       if (!draftRelease) {
+      #         core.setFailed(`No draft release found with tag ${versionTag}. Please create a draft release first.`);
+      #         return;
+      #       }
 
-            console.log(`Found draft release with tag ${versionTag} (ID: ${draftRelease.id})`);
+      #       console.log(`Found draft release with tag ${versionTag} (ID: ${draftRelease.id})`);
 
-      # Check if there is an open milestone for this version
-      # API: https://docs.github.com/en/rest/issues/milestones?apiVersion=2022-11-28#list-milestones
-      - name: Verify milestone
-        continue-on-error: ${{ inputs.force }}
-        env:
-          GEM_VERSION: ${{ steps.version.outputs.version }}
-        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
-        with:
-          script: |
-            const { data: milestones } = await github.rest.issues.listMilestones({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              state: 'open'
-            });
+      # # Check if there is an open milestone for this version
+      # # API: https://docs.github.com/en/rest/issues/milestones?apiVersion=2022-11-28#list-milestones
+      # - name: Verify milestone
+      #   continue-on-error: ${{ inputs.force }}
+      #   env:
+      #     GEM_VERSION: ${{ steps.version.outputs.version }}
+      #   uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+      #   with:
+      #     script: |
+      #       const { data: milestones } = await github.rest.issues.listMilestones({
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         state: 'open'
+      #       });
 
-            console.log(milestones);
+      #       console.log(milestones);
 
-            const versionMilestone = milestones.find(
-              milestone => milestone.title === process.env.GEM_VERSION
-            );
+      #       const versionMilestone = milestones.find(
+      #         milestone => milestone.title === process.env.GEM_VERSION
+      #       );
 
-            if (!versionMilestone) {
-              core.setFailed(`No open milestone found with title ${process.env.GEM_VERSION}. Please create a milestone first.`);
-              return;
-            }
+      #       if (!versionMilestone) {
+      #         core.setFailed(`No open milestone found with title ${process.env.GEM_VERSION}. Please create a milestone first.`);
+      #         return;
+      #       }
 
-            console.log(`Found open milestone ${process.env.GEM_VERSION} (ID: ${versionMilestone.number})`);
+      #       console.log(`Found open milestone ${process.env.GEM_VERSION} (ID: ${versionMilestone.number})`);
 
       # Check if the commit has passed all Github checks
       - name: Verify check runs
